# -*- coding: utf-8 -*-
"""
Plot the gold-denominated WPI figures: one chart per country plus a combined
5-country chart, with the annual index, centred 3/6/9-yr moving averages and
peak/trough markers (year labels written on the chart).

Inputs (regenerated by scripts/wpi_build_series.py):
    data/wpi_annual_1800_2026.json    annual gold-denominated WPI
    data/wpi_cycles_gold.json         peak/trough cycles on the 9-yr MA

Outputs (figures/):
    wpi_chart_US.png ... wpi_chart_FR.png        per-country charts (log y)
    wpi_chart_combined_9yMA_log.png              five countries, 9-yr MAs

Usage:
    python scripts/wpi_plot_charts.py
"""
import os, sys, json
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

sys.stdout.reconfigure(encoding="utf-8")
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # repo root
DATA = os.path.join(REPO, 'data')
FIG = os.path.join(REPO, 'figures')
os.makedirs(FIG, exist_ok=True)

plt.rcParams['font.sans-serif'] = ['DejaVu Sans', 'SimHei']
plt.rcParams['axes.unicode_minus'] = False

NAMES = {'US': 'United States', 'UK': 'United Kingdom', 'DE': 'Germany',
         'JP': 'Japan', 'FR': 'France'}
COLS = {'US': '#1f77b4', 'UK': '#d62728', 'DE': '#2ca02c', 'JP': '#9467bd',
        'FR': '#ff7f0e'}

def load():
    with open(os.path.join(DATA, 'wpi_annual_1800_2026.json'), encoding='utf-8') as f:
        ann_j = json.load(f)
    with open(os.path.join(DATA, 'wpi_cycles_gold.json'), encoding='utf-8') as f:
        cyc_j = json.load(f)
    rows = []
    for y in range(1800, 2027):
        r = {'year': y}
        for c in NAMES:
            r[f'goldwpi_{c}'] = ann_j['annual']['goldwpi'][c].get(str(y))
        rows.append(r)
    ann = pd.DataFrame(rows)
    cyc = {}
    for c in NAMES:
        cyc[c] = pd.DataFrame([{'year': p['year'], 'type': p['type'],
                                'ma9_value': p['ma9']} for p in cyc_j['cycles'][c]])
    return ann, cyc

def moving_avg(series, w):
    return series.rolling(w, center=True, min_periods=2).mean()

def plot_country(c, ann, cyc):
    s = ann[['year', f'goldwpi_{c}']].dropna()
    x = s['year'].values
    y = s[f'goldwpi_{c}'].values
    s_idx = s.set_index('year')[f'goldwpi_{c}']
    ma9 = moving_avg(s_idx, 9)
    fig, ax = plt.subplots(figsize=(15, 8), dpi=110)
    ax.plot(x, y, color='#bbbbbb', lw=1.0, label='Annual index', zorder=1)
    for w, col, lab, lw in [(3, '#1f77b4', '3-yr MA', 1.6),
                            (6, '#ff7f0e', '6-yr MA', 1.6),
                            (9, '#d62728', '9-yr MA', 2.6)]:
        ma = moving_avg(s_idx, w)
        ax.plot(ma.index, ma.values, color=col, lw=lw, label=lab, zorder=2)
    ax.set_title(f'{NAMES[c]}: Wholesale Price Index in Gold Terms (1913=100), '
                 f'{int(s.year.min())}-{int(s.year.max())}', fontsize=14)
    ax.set_xlabel('Year')
    ax.set_ylabel('Index (1913=100)')
    ax.set_yscale('log')
    ax.legend(loc='upper right', fontsize=10)
    ax.grid(alpha=0.3, which='both')
    fig.canvas.draw()
    ax.autoscale()
    ymin, ymax = ax.get_ylim()
    log_span = np.log10(ymax) - np.log10(ymin)

    bbox_kw = dict(boxstyle='round,pad=0.18', fc='white', alpha=0.85, ec='#888888', lw=0.5)
    for _, r in cyc[c].iterrows():
        yy = int(r['year'])
        if yy not in s['year'].values or yy not in ma9.index:
            continue
        v = float(ma9.loc[yy])
        pos = (np.log10(v) - np.log10(ymin)) / log_span
        if r['type'] == 'peak':
            ax.plot(yy, v, marker='^', color='#d62728', ms=12, zorder=6)
            dy = -18 if pos > 0.82 else 10
            ax.annotate(f'{yy} Peak', xy=(yy, v), xytext=(0, dy),
                        textcoords='offset points', ha='center', fontsize=10,
                        fontweight='bold', color='#d62728', bbox=bbox_kw,
                        clip_on=False, zorder=8)
        else:
            ax.plot(yy, v, marker='v', color='#1f77b4', ms=12, zorder=6)
            dy = 16 if pos < 0.18 else -18
            ax.annotate(f'{yy} Trough', xy=(yy, v), xytext=(0, dy),
                        textcoords='offset points', ha='center', fontsize=10,
                        fontweight='bold', color='#1f77b4', bbox=bbox_kw,
                        clip_on=False, zorder=8)
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, f'wpi_chart_{c}.png'), bbox_inches='tight')
    plt.close(fig)
    print('saved figures/wpi_chart_%s.png' % c)

def _overlaps(a, b, pad):
    ax0, ay0, ax1, ay1 = a
    bx0, by0, bx1, by1 = b
    return not (ax1 + pad < bx0 or bx1 + pad < ax0 or ay1 + pad < by0 or by1 + pad < ay0)

def plot_combined(ann, cyc):
    fig, ax = plt.subplots(figsize=(16, 9), dpi=110)
    for c in NAMES:
        s = ann[['year', f'goldwpi_{c}']].dropna()
        ma = moving_avg(s.set_index('year')[f'goldwpi_{c}'], 9)
        ax.plot(ma.index, ma.values, color=COLS[c], lw=2.0,
                label=f'{NAMES[c]} (9-yr MA)')
    ax.set_title('Wholesale Price Index in Gold Terms: 5 Countries, 9-yr Moving '
                 'Average (1913=100)', fontsize=14)
    ax.set_xlabel('Year')
    ax.set_ylabel('Index (1913=100)')
    ax.set_yscale('log')
    ax.legend(loc='upper right', fontsize=10)
    ax.grid(alpha=0.3, which='both')
    fig.canvas.draw()
    rend = fig.canvas.get_renderer()

    # Peak/trough markers (country colour, white edge) + year labels with
    # collision avoidance (placed in display-pixel space, 8 offset levels).
    bbox_kw = dict(boxstyle='round,pad=0.12', fc='white', alpha=0.85, ec='none', lw=0)
    placed = []
    for c in NAMES:
        s = ann[['year', f'goldwpi_{c}']].dropna()
        ma9 = moving_avg(s.set_index('year')[f'goldwpi_{c}'], 9)
        for _, r in cyc[c].iterrows():
            yy = int(r['year'])
            if yy not in ma9.index:
                continue
            v = float(ma9.loc[yy])
            is_peak = r['type'] == 'peak'
            ax.plot(yy, v, marker='^' if is_peak else 'v', color=COLS[c], ms=9,
                    markeredgecolor='white', markeredgewidth=0.8, zorder=6)
            candidates = [10, -16, 28, -34, 46, -52, 64, -70] if is_peak else \
                         [-16, 10, -34, 28, -52, 46, -70, 64]
            for dy in candidates:
                t = ax.annotate(f'{yy}', xy=(yy, v), xytext=(0, dy),
                                textcoords='offset points', ha='center', fontsize=8.5,
                                fontweight='bold', color='#222222', bbox=bbox_kw,
                                clip_on=False, zorder=8)
                bb = t.get_window_extent(rend)
                rect = (bb.x0, bb.y0, bb.x1, bb.y1)
                if not any(_overlaps(rect, p, 4) for p in placed):
                    placed.append(rect)
                    break
                t.remove()
    ax.text(0.01, 0.02, '▲ Peak    ▼ Trough    (labels = year of 9-yr MA extremum)',
            transform=ax.transAxes, fontsize=9, va='bottom', ha='left',
            bbox=dict(boxstyle='round,pad=0.3', fc='white', alpha=0.85, ec='#888888', lw=0.5))
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, 'wpi_chart_combined_9yMA_log.png'), bbox_inches='tight')
    plt.close(fig)
    print('saved figures/wpi_chart_combined_9yMA_log.png')

def main():
    ann, cyc = load()
    for c in NAMES:
        plot_country(c, ann, cyc)
    plot_combined(ann, cyc)

if __name__ == '__main__':
    main()
